### ISSUE TITLE
how to install it on UBUNTU vps 

### ISSUE THREAD

**Issue by ingnelson** [maurice2k/moproxy#1]
Hello.

can you give me the command to install it and run it on Ubuntu VPS , please ?

i would like to use it.

**Comment by maurice2k** [comment]
Hi ingnelson,

please be aware that moproxy is still under heavy development which means I'm still breaking things like config settings etc.

I'm going to update the whole project and add a README with installation instructions within the next days.

**Comment by ingnelson** [comment]
@maurice2k perfect , I would like to use it on a Ubuntu VPS , if it is posible add all the commands to Install it and run it on Ubuntu vps README .

I tell that  because there are projects that only few people can use it , because only they are programmer , normal people can not use it , it is useful the command or just a a auto script to install and run the proxy.

I am going to wait .

**Comment by maurice2k** [comment]
Install is easy with
```
# make
# make install
```
Installs to `/opt/moproxy` by default and registers a systemd service.
You need go > 1.11 installed for that.

You also need to adjust the config in `/opt/moproxy/configs` (have a look at `moproxy.conf.dist` as a reference).

Not sure what you're really looking after. Maybe it's easier to setup a proxy using `apt` on your ubuntu box.
